import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <title>Oursummit</title>
            <body className={inter.className}>
                <nav>
                    <div className="logo">
                        <Image
                            src="/Oursummit_logo.svg"
                            alt="Oursummit Logo"
                            width={280}
                            height={280}
                            priority
                        />
                    </div>

                    <div className="links">
                        <a className="link btn-100" href="/home">Home</a>
                        <a className="link btn-100" href="/about">About</a>
                    </div>
                    <a className="link btn-100">Je m'inscris</a>

                </nav>
                {children}
            </body>
        </html>
    );
}
